[build]
  publish = "public"

[[redirects]]
  from = "/emeraldprize"
  to = "/emeraldprize.html"
  status = 200

[[redirects]]
  from = "/emeraldprize/terms"
  to = "/emeraldprize-terms.html"
  status = 200

[[redirects]]
  from = "/aibfc"
  to = "/aibfc.html"
  status = 200

[[redirects]]
  from = "/prep"
  to = "/aibfc-prep.html"
  status = 200

[[redirects]]
  from = "/aispc"
  to = "/aispc.html"
  status = 200

[[redirects]]
  from = "/aispc/*"
  to = "/aispc.html"
  status = 200

[[redirects]]
  from = "/tour"
  to = "/tour.html"
  status = 200

[[redirects]]
  from = "/tour/*"
  to = "/tour.html"
  status = 200

[[redirects]]
  from = "/competitions"
  to = "/competitions.html"
  status = 200

[[redirects]]
  from = "/competitions/*"
  to = "/competitions.html"
  status = 200

# emeraldprize.com domain
[[redirects]]
  from = "https://emeraldprize.com/terms"
  to = "/emeraldprize-terms.html"
  status = 200
  force = true

[[redirects]]
  from = "https://www.emeraldprize.com/terms"
  to = "/emeraldprize-terms.html"
  status = 200
  force = true

[[redirects]]
  from = "https://emeraldprize.com/*"
  to = "/emeraldprize.html"
  status = 200
  force = true

[[redirects]]
  from = "https://www.emeraldprize.com/*"
  to = "/emeraldprize.html"
  status = 200
  force = true

[[redirects]]
  from = "https://aibfc.org/prep"
  to = "/aibfc-prep.html"
  status = 200
  force = true

[[redirects]]
  from = "https://www.aibfc.org/prep"
  to = "/aibfc-prep.html"
  status = 200
  force = true

[[redirects]]
  from = "https://aibfc.org/*"
  to = "/aibfc.html"
  status = 200
  force = true

[[redirects]]
  from = "https://www.aibfc.org/*"
  to = "/aibfc.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
